### ISSUE TITLE
Prevent editing after due date

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#1]
The frontend should indicate the remaining time for an exercise and block the user from further editing her/his solution when the due date is reached (server side due date!).

**Comment by leMaik** [comment]
May the client time be used for displaying the remaining time? The client could then send a request in regular intervals to check if the due date is over.

**Comment by LittleHelicase** [comment]
It is important that the displayed remaining time is the correct one (if the user does not hack the frontend). Currently I think a possible solution would be.

1. Get exericse (including dueDate).
2. Get servier time and calculate difference between server time and user time (using moment.js)
   `difference = serverTime.subtract(userTime)`
3. Display time via `currentServerTime = userTime.add(difference)`
4. Regularly (every minute or so) update server time and difference.

We probably will close the Web Sockets connections a minute after the user will get the "due date reached" message to ensure that nothing is lost on the way. One minute will hopefully not decide the fate of the student ;).

**Comment by leMaik** [comment]
Wow, that's a bit more complex than I first thought. The websockets don't need to be closed immediately as the server could simply save a snapshot of the user's solution when the time is over.
