### ISSUE TITLE
Display test status of the focused task under the editor

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-student#11]
Title says it all, the bar is already there.

**Comment by LittleHelicase** [comment]
Tests now run with 35720a62319ec38b1d28ab4710907e4cb150f92d (except for #15 ). But the popup doesn't update properly. I'm pretty confident that I set the results correctly (at least the thumbs symbol indicates that the tests are okay). The popup itself does not.. Perhaps a semantic-ui issue?

**Comment by LittleHelicase** [comment]
I just updated the MemDB version to include a valid example with a test.

**Comment by leMaik** [comment]
Definetly not a semantic ui issue. I'll look into this tomorrow. Could you please open a ticket?

**Comment by leMaik** [comment]
The editor seems to be completely broken right now.

**Comment by LittleHelicase** [comment]
Possibly because of an outdated memorydb..

**Comment by leMaik** [comment]
I fixed it, let's see if my "fix" now breaks when I update memorydb. :/
