### ISSUE TITLE
Create a FavIcon

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#14]
The console is always complaining that there is no favicon ;). I always see some other favicon that was once on the same port which is a bit confusing.

**Comment by leMaik** [comment]
I would really like to create one in Material style, with long shadows. :)

**Comment by leMaik** [comment]
![corrector](https://cloud.githubusercontent.com/assets/5544859/10416402/545af25a-7016-11e5-82a5-d45ba4964272.png)
![tutor](https://cloud.githubusercontent.com/assets/5544859/10416404/56157412-7016-11e5-8ad6-a64ce426ddc4.png)
![lecturer](https://cloud.githubusercontent.com/assets/5544859/10416405/579aae74-7016-11e5-8a83-1699d7ae2b9f.png)

**Comment by LittleHelicase** [comment]
Neat..

**Comment by leMaik** [comment]
So... Want to have them as SVG?

**Comment by LittleHelicase** [comment]
http://caniuse.com/#feat=link-icon-svg

We should probably use a normal .ico version..

**Comment by leMaik** [comment]
Oh, okay... I'll create a repo for the icons in various formats.
