### ISSUE TITLE
Process markdown even with JS errors

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#15]
For some reason the markdown processor stops, when the js source in the markdown contains syntax errors. This could probably be because of esprima and an uncaught exception.

**Comment by LittleHelicase** [comment]
Fixed that one. Esprima was missing. Now esprima checks if the Syntax is correct and if not the tests won't run.

**Comment by leMaik** [comment]
Did this also fix the broken error highlighting?

**Comment by LittleHelicase** [comment]
Sadly, no...
