### ISSUE TITLE
Test result popup should display the most recent results

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#16]
When an exercise contains tests the editor stars all tests and stores the results in `@allTests`. They are currently updated one by one:

1. After changing the contents of one task, all test results are removed.
2. All tests are registered as `not passing`. This is important, as this stage does not include the users (probably syntactically incorrect) source code and thus every test is recognized if the tests are syntactically correct. In this stage every registered test updates the allTests array.
3. Run the tests and update all the results

In this process, not every passing test gets a checkmark in the popup, as intended.

**Comment by leMaik** [comment]
We need to fix #18 in order to fix this.

**Comment by leMaik** [comment]
Okay, it now shows the correct exercises. Problem: The popup shows nothing until you click inside any editor the first time (and after that it works as expected). See #19.

**Comment by LittleHelicase** [comment]
I fixed that one.

The problem was, that multiple edits created multiple changes and they got in their own way. I now only update the test box when all tests are finished. It looks good, but when loading the site it sometimes does not display the correct test status. But after changing something in the editor it reliably shows the correct results.
