### ISSUE TITLE
Getting the selected tasks only works if it contains a test

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-student#18]
...and it's the most ugly hack I've seen so far in Tutor. :laughing:

**Comment by LittleHelicase** [comment]
Can you be more specific. What do you mean by "Getting the selected task" ?

**Comment by leMaik** [comment]
I mean that the selectedTaskIndex is set after the tests were processed, which does not seem to work. Also, it is not reset to `-1` if no ace editor is selected.

**Comment by LittleHelicase** [comment]
The selectedTaskIndex seems to select the correct task for me. I didn't use the Ace callback until now, I only wanted to see if it works. But it didn't update correctly. I can change this later, but probably not today.

**Comment by leMaik** [comment]
It always selects task 0 for me and never changes. And it does not change if you select no task. I'll fix it right now, using ace events (focus and blur)...
