### ISSUE TITLE
Close connections to documents after due date

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#2]
All open web sockets to the ShareJS document must be closed and the user must be unable to reconnect to those documents after the due date is reached (using server time ;) ).

**Comment by LittleHelicase** [comment]
If a student somehow manages to continue writing, we store those edits, but don't take them into account for the evaluation. This is possible because sharejs stores editing time for every edit.

The problem with checking the status of the exercise are the constant queries to the DB to get the due date of the exercise. We could store the due date on the servers but that would involve some kind of caching mechanism.

**Comment by leMaik** [comment]
The edits themselves already in involve lots of queries, so is this actually a problem? On the other hand, it would probably duplicate the number of queries...

**Comment by leMaik** [comment]
The client can be manipulated, but it's something. Also, the client won't try to reconnect if the connection is closed by the server and the due date has come.

**Comment by LittleHelicase** [comment]
The nginx server closes the connection frequently (currently every minute), so we don't need to track them explicitly in the student server. It will fail if the websocket is reconnected.

**Comment by fasib** [comment]
tutor-share-ace-rethinkdb v0.7.2 has now a due date check
https://github.com/Welfenlab/tutor-share-ace-rethinkdb/blob/master/share-ace-server.js#L36
