### ISSUE TITLE
Errors hints in the editor should update correctly

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#24]
Currently the error highlighting is disabled, but when enabled it looks like this:

![image](https://cloud.githubusercontent.com/assets/5698911/10450886/58ad6f9e-719d-11e5-88ab-27132b3338cb.png)

Responsible package: https://github.com/Welfenlab/javascript-editor-errors

**Comment by leMaik** [comment]
Fixed as of 53e5cd.
