### ISSUE TITLE
student/shareJS should work without rethinkdb

### ISSUE THREAD

**Issue by fasib** [Welfenlab/tutor-student#25]
It would be great if you could start this project without rethinkdb.

There should be an option within the config file to change this behaviour.

[database]( https://github.com/Welfenlab/tutor-student/blob/master/config.cson#L19) and [sharejs]( https://github.com/Welfenlab/tutor-student/blob/master/config.cson#L31)

```
[...]
database:
  host : "srv2"
  port : 28015
  name : "TutorDB"
[...]
sharejs:
  rethinkdb:
    host: "srv2"
    port: 28015
    name: "ShareJS"
[...]
```

**Comment by leMaik** [comment]
ShareJS can use a memory-database like this:
```js
var livedb = require('livedb');
var sharejs = require('share');

var backend = livedb.client(livedb.memory());
var share = require('share').server.createClient({backend: backend});
```

**Comment by fasib** [comment]
student now works again just with `node index.js` without a RethinkDB connection
