### ISSUE TITLE
Show results for user

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#29]
The Overview page only shows active and finished exercises, but not the points, the results etc.

We need
- [x] Overall points (Percentage of points (per exercise and total, with a progress bar)
- [x] a checkmark if you still get the bonus
- [x] Submission PDF
- [x] Corrected PDF
- [x] Points per exercise
- [x] The remaining time for all active exercises (only for usability)

more?

**Comment by fasib** [comment]
- total points
- special text for the top 3 groups?

**Comment by leMaik** [comment]
Percentage of points (per exercise and total, with a progress bar) and a checkmark if you still get the bonus. The interface for the "Introduction to database programming" lecture has this and it was pretty useful.

**Comment by LittleHelicase** [comment]
Yeah the badge etc. is something for later ;).

**Comment by leMaik** [comment]
:white_check_mark: Done.
