### ISSUE TITLE
"Eat" any stack traces

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-student#32]
If the server returns any non-2xx code, the response should be removed and logged. Stack traces may contain sensible information.
This could be done using express middleware.

**Comment by fasib** [comment]
Right now they are created by the student-server [promised_callback.coffee#L13](https://github.com/Welfenlab/tutor-server/blob/master/src/promised_callback.coffee#L13).

**Comment by leMaik** [comment]
So this is a feature and not a bug? :open_mouth: Isn't there a configuration option to switch into production mode? Or could we detect this?

**Comment by fasib** [comment]
Yes there is a configuration option to switch into production mode, but it is not used right now there.

**Comment by LittleHelicase** [comment]
The final container sets the environment variable NODE_ENV to "production" you can query this by

```
if(process.env.NODE_ENV === "production")...
```

It is rather easy to implement a silent error handler. I thaught that it was the standard behaviour of express in production, but it seems to not be the case.

**Comment by fasib** [comment]
It should be possible to hide the output via nginx [proxy_intercept_errors](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_intercept_errors) and [error_page](http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page).

**Comment by leMaik** [comment]
Isn't this the wrong place to do that?

**Comment by LittleHelicase** [comment]
I think the question is, could there be a case where we forget to "not send" errors. And would it be necessary to add a nginx solution for that ?

**Comment by LittleHelicase** [comment]
It seems that this one is fixed. I always get "Internal Server Error" but nothing more, if there is a problem with my API call.
