### ISSUE TITLE
prefill the sharejs document when its created

### ISSUE THREAD

**Issue by fasib** [Welfenlab/tutor-student#33]
When a new task is opened for the first time (and/or the sharejs document is empty?) then it should contain the prefilled text from the task.

**Comment by LittleHelicase** [comment]
I'm pretty confident that it works like this. If it is a new document it will get the "preffiled" value.

**Comment by fasib** [comment]
the input should be deselected

**Comment by leMaik** [comment]
FYI: The input is also selected if the document already existed and contains a solution.

**Comment by leMaik** [comment]
This could be closed, right?

**Comment by fasib** [comment]
Hmm i'm not sure right now if that should happen or not. A user could accidentally delete everything that was prefiled (hints, etc.) and would need to undo the change (:arrow_right: more traffic?).
I would propose to disable the initial selection even if it already contains a solution.

**Comment by fasib** [comment]
Okay i didn't check if it gets deselected right now
