### ISSUE TITLE
Browserified files should contain absolute paths

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-student#37]
Strings like `/home/maik/Gits/tutor-meta/tutor-student/node_modules/...` should not appear in any distributed files.

**Comment by leMaik** [comment]
Even better than configuring browserify not to include full paths: https://www.npmjs.com/package/unpathify

**Comment by LittleHelicase** [comment]
Did you check that your change didn't break the discify builder. It requires full paths to analyze the packages.

**Comment by leMaik** [comment]
The plugin only works if `fullPaths: false`, which is only set if `NODE_ENV == "production"`, so discify will work.
