### ISSUE TITLE
Declined or accepted invitations are not removed

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-student#38]
When the user accepts an invitation, their group is set correctly but the invitation is not removed. When the user declines an invitation, nothing happens.

**Comment by 5cript** [comment]
This is strange, because I cannot reproduce it with tests.

**Comment by 5cript** [comment]
#36 is basically the same.
... I will look into this once more, but its still strange.

**Comment by 5cript** [comment]
Duplicate of #36 - no also closed.
