### ISSUE TITLE
Group join request returns wrong data

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-student#39]
When the user "Lazy Dijkstra" accepts an invite, this data is returned:
`{"name":"pending group","id":"fd8c6b08-572d-11e5-9824-685b35b5d746","users":["Tiny Knuth","Lazy Dijkstra"],"pendingUsers":["Lazy Dijkstra"]}`

But "Lazy Dijkstra" should not appear twice! Expected output:
`{"name":"pending group","id":"fd8c6b08-572d-11e5-9824-685b35b5d746","users":["Tiny Knuth","Lazy Dijkstra"],"pendingUsers":[]}`

**Comment by 5cript** [comment]
please recheck.

**Comment by leMaik** [comment]
:+1:
