### ISSUE TITLE
Find out if the exercises where corrected by a tutor

### ISSUE THREAD

**Issue by fasib** [Welfenlab/tutor-student#41]
Currently there is now way to find out if a exercise was corrected by a tutor or not.
'api/exercises' should also output a field that indicates the current status

**Comment by LittleHelicase** [comment]
I think there is a flag in the solution call `api/solution/:id` there is a flag `lock` that indicates which tutor locked the solution. It is only set if the solution was corrected. It is possible that the example set does not contain such a flag, but it is implemented.

**Comment by leMaik** [comment]
I'm not sure if checking if a solution is corrected should work by looking at a flag that is meant for locking the exercise (the student shouldn't see the lock).

Anyway, that flag (and the correction status) is not included in `/api/exercises/`. I'd need it there (see 14f3b26) for the student's overview. Also, the points the student got for each exercise should be included.

**Comment by leMaik** [comment]
The exercises get a `corrected` attribute that is set to `true` after correcting as of Welfenlab/tutor-rethinkdb-database@268e2fd28459610cac46de7f0e7821093530dced and this is used to check if the exercise is corrected since last friday, so this issue is finally resolved. :+1:
