### ISSUE TITLE
Create a module that handels the server time

### ISSUE THREAD

**Issue by fasib** [Welfenlab/tutor-student#43]
See:
[app/scripts/pages/exercises/exercises.coffee#L14](https://github.com/Welfenlab/tutor-student/blob/master/app/scripts/pages/exercises/exercises.coffee#L14)
[app/scripts/pages/editor/editor.coffee#L58](https://github.com/Welfenlab/tutor-student/blob/master/app/scripts/pages/editor/editor.coffee#L58)

**Comment by leMaik** [comment]
@fasib Done, please re-open if it doesn't work or doesn't fit your needs. ;-)
