### ISSUE TITLE
Support multiple editors

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#45]
The new package does not work if there are multiple edtiors (e.g. for multiple tasks). It only updates the last one. Initially I have the rendered markdown of the first task in the last task. After editing I only see the solution of the last task in the last task..

![image](https://cloud.githubusercontent.com/assets/5698911/11470317/e4ea7ecc-975c-11e5-866d-0d69fa448c93.png)

**Comment by leMaik** [comment]
Fixed.
