### ISSUE TITLE
Style for tables

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#46]
We need a style for tables that looks more like  table than the current one.

![image](https://cloud.githubusercontent.com/assets/5698911/11475035/8a3bf2ac-977b-11e5-9095-8c25a7ebfb97.png)

The writ style looks like this.

![image](https://cloud.githubusercontent.com/assets/5698911/11475102/db0d7ad4-977b-11e5-8312-4b6127c493a2.png)

**Comment by leMaik** [comment]
This should be done in Welfenlab/tutor-exercise-preview to ensure that the markdown looks the same everywhere (the stylesheet will be included there).

**Comment by leMaik** [comment]
Done. :+1: 
We could put the style into tutor-task-preview later.
