### ISSUE TITLE
Power mode

### ISSUE THREAD

**Issue by fasib** [Welfenlab/tutor-student#53]
It would be awesome if we could add the power mode to the editor.
See [codeinthedark/editor](https://github.com/codeinthedark/editor) (implemented for the ace editor) and an example for atom ([activate-power-mode atom package](https://github.com/JoelBesada/activate-power-mode)):
![](https://cloud.githubusercontent.com/assets/688415/11615565/10f16456-9c65-11e5-8af4-265f01fc83a0.gif) (atom)

**Comment by leMaik** [comment]
Implemented, simply use the ":rocket: button" to toggle power mode.
