### ISSUE TITLE
Alert when closing page tab and there are pending ShareJS updates

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#55]

**Comment by leMaik** [comment]
![image](https://cloud.githubusercontent.com/assets/5544859/11768585/f52c4d0e-a1d1-11e5-8063-f55fdfd5d551.png)
ShareJS doesn't correctly update the `pending` attribute when it is disconnected. Thus, this message is also shown if the user leaves the page when ShareJS is disconnected.

**Comment by LittleHelicase** [comment]
@fasib Is there a way to distinguish a closed ShareJS connection with no pending local changes from a closed connection with pending local changes?

E.g. I only looked at it for a while and the connection closed against I wrote a few lines after the disconnect.

**Comment by leMaik** [comment]
We can already distinguish that, but unfortunately the number of pending changes is not increased by ShareJS when not connected.

**Comment by leMaik** [comment]
I just looked at the [ShareJS API](https://github.com/share/ShareJS/wiki/Client-API/1593f9f9a35dfd87f8552176eab9990f92fd3546). We would need to put all ops that arrive in the `change` event went into an array (and remove any remote ops that we get from `remoteop` events) and remove them when they are acknowledged (`acknowledge` event). This way, we would construct an array of unacknowledged local changes (which ShareJS should do on its own already).
