### ISSUE TITLE
Changing the pseudonym should update the UI

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#6]
After changing the pseudonym the UI isn't updated. It leads to strange problems esp. in the group creation.

**Comment by leMaik** [comment]
What exactly do you mean? Currently, changing the pseudonym is not implemented at all.

**Comment by LittleHelicase** [comment]
Well, I did show the `#result` screen added a button and it works.. except the immediate update in the UI.

**Comment by leMaik** [comment]
Okay, changing the pseudonym is indeed implemented and this bug will be fixed in a moment. But which button do you mean, which link?

**Comment by leMaik** [comment]
At least with memory database, the server returns `Error 409: Pseudonym Flawless Lovelace already locked`. That's right, but it was locked for the current user...
