### ISSUE TITLE
PDF API request should get solution by exercise id

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#67]
The current PDF GET request takes the solution id and returns the PDF if it exists. But the request should only take the exercise id and use the session to infer the correct solution id.

**Comment by leMaik** [comment]
Note: The client already sends the exercise id.

**Comment by LittleHelicase** [comment]
Resolved in 8ef8e0975218ab6645230a8e0d82b3c4ea39d756
