### ISSUE TITLE
Choosing a pseudonym does not work

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-student#7]
At least with memory database, the server returns `Error 409: Pseudonym Flawless Lovelace already locked`. That's right, but it was locked for the current user...

**Comment by LittleHelicase** [comment]
I just tested it with rethinkdb.. It worked

**Comment by leMaik** [comment]
It would be nice if it also worked with the memory database, but that's not important...

**Comment by 5cript** [comment]
A new version has been published. Which contains a bugfix.
