### ISSUE TITLE
Put remaining time and "All things stored" above the editor

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#9]
I would recommend putting the "All things stored on the server" message and the remaining time above the exercise. Those information are not that important. I would like to put the results of the tests into the footer...

I will try to put the results into the footer today (probably in a non fancy fashion)

**Comment by leMaik** [comment]
"Put it above the exercise [...] those information are not that important." ... So why would you put them to the top?

**Comment by LittleHelicase** [comment]
They are not important while writing. You see the footer all the time. You don't need to see the "remaining time" all the time. The tests on the other hand are something you work with. You immediately want to see if they pass and thus it should always be on the screen (e.g. the footer).

**Comment by leMaik** [comment]
Yes, but maybe we can simply show everything? I'd say that two bars are a little too much. Maybe we can display the remaining time only if there is not much time left (< 1 day) and only show the clock icon (with a popup) if there is more time left?

**Comment by LittleHelicase** [comment]
The above bar wouldn't be visible if you scroll down. And I would like to separate the tests for every task. I wouldn't add extra logic for when the remaining time is visible or not.

**Comment by leMaik** [comment]
Sou you want to display a bar for each task? Or how should this be done?

I agree with the above bar stuff, I'll do that later.

**Comment by LittleHelicase** [comment]
Not a bar simply like this:
![image](https://cloud.githubusercontent.com/assets/5698911/10392012/916d0a46-6e83-11e5-8917-39d67de9f547.png)

And perhaps if you hover over it you see more?

**Comment by leMaik** [comment]
Have you already started? I'd like to do that in a moment, looks good! :-)

**Comment by LittleHelicase** [comment]
No I didn't. Thumbs up is better than checkmarks.
